### ISSUE TITLE
[AVM Module Issue]: 🐛 error about legacy module

### ISSUE THREAD

**Issue by Laffs2k5** [Azure/terraform-azurerm-avm-res-network-natgateway#32]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Module specific issue

- [X] I confirm that this issue is about this AVM module and not about the resource itself, or how to use Terraform.

### Issue Type?

Bug

### (Optional) Module Version

0.1.0

### Description

Hi,

The currently latest release `0.1.0` includes provider configuration for azurerm in [`terraform.tf`](https://github.com/Azure/terraform-azurerm-avm-res-network-natgateway/blob/v0.1.0/terraform.tf#L16-L18).

This results in errors like this from terraform during init:
```log
Initializing modules...
Downloading registry.terraform.io/Azure/avm-res-network-natgateway/azurerm 0.1.0 for main.common_management.mgmt_outbound_nat_gw...
- main.common_management.mgmt_outbound_nat_gw in .terraform/modules/main.common_management.mgmt_outbound_nat_gw
╷
│ Error: Module is incompatible with count, for_each, and depends_on
│ 
│   on ../../main/main.tf line 540, in module "common_management":
│  540:   for_each = var.common_management_network_configuration != null ? toset([var.environment]) : []
│ 
│ The module at module.main.module.common_management.module.mgmt_outbound_nat_gw is a legacy module which contains its own local provider configurations, and so calls to it may not use
│ the count, for_each, or depends_on arguments.
│ 
│ If you also control the module "registry.terraform.io/Azure/avm-res-network-natgateway/azurerm", consider updating this module to instead expect provider configurations to be passed by
│ its caller.
╵
```

I see that in commit [0ad7de3](https://github.com/Azure/terraform-azurerm-avm-res-network-natgateway/commit/0ad7de32130d5cccca4e343ef014c685e2bcba16) the provider configuration was removed. The issue is that these changes were never included in a release.

Please consider releasing a new version of this module.

**Comment by segraef** [comment]
Hi @Laffs2k5, in the provider was removed from [0.1.0 to 0.1.1](https://github.com/Azure/terraform-azurerm-avm-res-network-natgateway/compare/v0.1.0...v0.1.1) and is reflected in the published version [0.1.1](https://registry.terraform.io/modules/Azure/avm-res-network-natgateway/azurerm/0.1.1).

CC @mbilalamjad
